shinyUI(fluidPage(
  titlePanel("Exploring the Probability of Democracy Data Set"),
  
  sidebarLayout(position = "right",
    
    sidebarPanel(
      
      selectInput("countryname", h4("Country:"),
                  choices = c(
                    "Afghanistan" = "Afghanistan",
                    "Albania" = "Albania",
                    "Algeria" = "Algeria",
                    "Angola" = "Angola",
                    "Argentina" = "Argentina",
                    "Armenia" = "Armenia",
                    "Australia" = "Australia",
                    "Austria" = "Austria",
                    "Azerbaijan" = "Azerbaijan",                    
                    "Bahrain" = "Bahrain",
                    "Belgium" = "Belgium",
                    "Benin" = "Benin",
                    "Burkina Faso" = "Burkina Faso",                     
                    "Bhutan" = "Bhutan",
                    "Belarus" = "Belarus",
                    "Bangladesh" = "Bangladesh",
                    "Bolivia" = "Bolivia",
                    "Bosnia and Herzegovina" = "Bosnia and Herzegovina",
                    "Botswana" = "Botswana",
                    "Brazil" = "Brazil",
                    "Burundi" = "Burundi",
                    "Bulgaria" = "Bulgaria",
                    "Cambodia" = "Cambodia",
                    "Canada" = "Canada",                        
                    "Cameroon" = "Cameroon",
                    "Central African Republic" = "Central African Republic",
                    "Chad" = "Chad",
                    "Chile" = "Chile",
                    "China" = "China",
                    "Colombia" = "Colombia",
                    "Comoros" = "Comoros",
                    "Congo, Republic of" = "Congo-Brazzaville",
                    "Congo, Democratic Republic of" = "Congo-Kinshasa",
                    "Costa Rica" = "Costa Rica",
                    "Cote d'Ivoire" = "Ivory Coast",
                    "Croatia" = "Croatia",
                    "Cuba" = "Cuba",
                    "Cyprus" = "Cyprus",
                    "Czechoslovakia" = "Czechoslovakia",
                    "Czech Republic" = "Czech Republic",
                    "Denmark" = "Denmark",
                    "Djibouti" = "Djibouti",
                    "Dominican Republic" = "Dominican Republic",            
                    "Ecuador" = "Ecuador",
                    "El Salvador" = "El Salvador",
                    "Egypt" = "Egypt",
                    "Equatorial Guinea" = "Equatorial Guinea",
                    "Eritrea" = "Eritrea",
                    "Estonia" = "Estonia",
                    "Ethiopia" = "Ethiopia",
                    "Finland" = "Finland",                       
                    "Fiji"= "Fiji",
                    "France" = "France",
                    "Gabon" = "Gabon",
                    "Gambia" = "Gambia",
                    "Germany, East" = "East Germany",
                    "Germany, West" = "West Germany",
                    "Germany" = "Germany",                       
                    "Ghana" = "Ghana",
                    "Guinea-Bissau" = "Guinea-Bissau",
                    "Greece"= "Greece",
                    "Georgia" = "Georgia",
                    "Guatemala" = "Guatemala",
                    "Guinea" = "Guinea",
                    "Guyana" = "Guyana",
                    "Haiti" = "Haiti",
                    "Honduras" = "Honduras",
                    "Hungary" = "Hungary",
                    "India" = "India",
                    "Indonesia" = "Indonesia",
                    "Ireland" = "Ireland",
                    "Iran" = "Iran",
                    "Iraq" = "Iraq",
                    "Israel"= "Israel",
                    "Italy" = "Italy",
                    "Jamaica" = "Jamaica",
                    "Jordan" = "Jordan",
                    "Japan" = "Japan",
                    "Kenya" = "Kenya",
                    "Korea, North" = "North Korea",
                    "Korea, South" = "South Korea",
                    "Kuwait" = "Kuwait",
                    "Kyrgyzstan" = "Kyrgyzstan",
                    "Kazakhstan" = "Kazakhstan",
                    "Laos" = "Laos",                          
                    "Latvia" = "Latvia",
                    "Liberia" = "Liberia",
                    "Lebanon" = "Lebanon",
                    "Lesotho" = "Lesotho",
                    "Libya" = "Libya",
                    "Lithuania" = "Lithuania",
                    "Mauritania" = "Mauritania",
                    "Macedonia" = "Macedonia",
                    "Madgascar" = "Madagascar",
                    "Malaysia"= "Malaysia",
                    "Mauritius" = "Mauritius",
                    "Malawi" = "Malawi",                        
                    "Mexico" = "Mexico",
                    "Moldova" = "Moldova",
                    "Mali" = "Mali",
                    "Montenegro" = "Montenegro",
                    "Mongolia" = "Mongolia",
                    "Morocco" = "Morocco",
                    "Myanmar" = "Myanmar",
                    "Mozambique" = "Mozambique",
                    "Namibia" = "Namibia",
                    "Nepal" = "Nepal",
                    "New Zealand" = "New Zealand",
                    "Nicaragua" = "Nicaragua",                     
                    "Niger" = "Niger",
                    "Nigeria" = "Nigeria",
                    "Norway" = "Norway",
                    "Netherlands" = "Netherlands",
                    "Oman" = "Oman",
                    "Pakistan" = "Pakistan",
                    "Panama" = "Panama",
                    "Paraguay" = "Paraguay",
                    "Peru" = "Peru",                          
                    "Philippines" = "Philippines",
                    "Papua New Guinea" = "Papua New Guinea",
                    "Poland" = "Poland",                        
                    "Portugal" = "Portugal",
                    "Qatar" = "Qatar",                         
                    "Romania" = "Romania",
                    "Russia" = "Russia",                        
                    "Rwanda" = "Rwanda",
                    "South Africa" = "South Africa",                  
                    "Saudi Arabia" = "Saudi Arabia",
                    "Senegal" = "Senegal",
                    "Serbia" = "Serbia",
                    "Serbia and Montenegro" = "Serbia and Montenegro",
                    "Sierra Leone" = "Sierra Leone",
                    "Singapore" = "Singapore",
                    "Slovakia" = "Slovakia",
                    "Slovenia" = "Slovenia",
                    "Solomon Islands" = "Solomon Islands",
                    "Somalia" = "Somalia",
                    "South Sudan" = "South Sudan",
                    "Spain" = "Spain",
                    "Sri Lanka" = "Sri Lanka",
                    "Sudan" = "Sudan",
                    "Swaziland" = "Swaziland",
                    "Sweden" = "Sweden",
                    "Switzerland" = "Switzerland",
                    "Syria" = "Syria",
                    "Tajikistan" = "Tajikistan",
                    "Taiwan" = "Taiwan",
                    "Tanzania" = "Tanzania",                      
                    "Thailand" = "Thailand",
                    "Timor Leste" = "Timor Leste",
                    "Togo" = "Togo",
                    "Trinidad and Tobago" = "Trinidad and Tobago",
                    "Tunisia" = "Tunisia",
                    "Turkey" = "Turkey",
                    "Turkmenistan" = "Turkmenistan",
                    "Uganda" = "Uganda",
                    "Ukraine" = "Ukraine",
                    "United Arab Emirates" = "United Arab Emirates",
                    "United Kingdom" = "United Kingdom",
                    "United States of America" = "United States",     
                    "Uruguay" = "Uruguay",           
                    "USSR" = "Soviet Union",
                    "Uzbekistan" = "Uzbekistan",
                    "Venezuela" = "Venezuela",                           
                    "Vietnam, North" = "North Vietnam",
                    "Vietnam, South" = "South Vietnam",
                    "Vietnam" = "Vietnam",
                    "Yemen, North" = "North Yemen",
                    "Yemen, South" = "South Yemen",
                    "Yemen" = "Yemen",
                    "Yugoslavia" = "Yugoslavia", 
                    "Yugoslavia, Federal Rep of" = "Federal Republic of Yugoslavia", 
                    "Zambia" = "Zambia",
                    "Zimbabwe" = "Zimbabwe"),
                  selected = "Russia", multiple = FALSE, selectize = TRUE, width = NULL),
      
      numericInput("startyear", h5("Start Year"), value = 1992, min = 1945, max = 2010),
      
      numericInput("endyear", h5("End Year"), value = 2010, min = 1945, max = 2010)

      ),
    
    mainPanel(
      p("Use this app to explore the Probability of Democracy Data Set developed by Jay Ulfelder
        and Sean J. Taylor. The app plots the probability of democracy and its 95% credible intervals
        for the selected country as estimated by a Bayesian measurement model derived from five existing
        binary indicators of democracy status."),
      br(),
      plotOutput("lineplot")
    )
    
)))
